spring.application.name=caparana

#BD CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


##SPRING SECURITY CONFIGURATION
spring.security.user.name=${SS_USERNAME}
spring.security.user.password=${SS_PASSWORD}

##CONFIGURACION DE JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}